services:
  - type: web
    name: road-defect-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app --timeout 600 --workers 1
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: data_volume
      mountPath: /data
      sizeGB: 1
